/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.empleado;

import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;
import utp.edu.pe.dao.daoEmpleados;
import utp.edu.pe.entity.empleado;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class actualizarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form crearEmpleado
     */
    public actualizarEmpleado() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApePatEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApeMatEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNroDocEmpleado = new javax.swing.JTextField();
        txtTipoDocEmpleado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNroTelefono1Empleado = new javax.swing.JTextField();
        txtNroTelefono2Empleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmailEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCargoEmpleado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtFNacimientoEmpleado = new javax.swing.JFormattedTextField();
        btnGuardar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));
        setPreferredSize(new java.awt.Dimension(770, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Actualizar empleado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setText("NOMBRE :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 95, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 758, 10));

        jLabel3.setText("APELLIDO PATERNO :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 175, -1, -1));
        add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 117, 687, 40));
        add(txtApePatEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 197, 320, 40));

        jLabel4.setText("APELLIDO MATERNO :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 175, -1, -1));
        add(txtApeMatEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 197, 320, 40));

        jLabel5.setText("TIPO DOCUMENTO :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 255, -1, -1));

        jLabel6.setText("NÚMERO DOCUMENTO :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 255, -1, -1));
        add(txtNroDocEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 277, 320, 40));

        txtTipoDocEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "DNI", "RUC", "CE" }));
        add(txtTipoDocEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 277, 320, 40));

        jLabel7.setText("TELÉFONO 1 :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 335, -1, -1));

        jLabel8.setText("TELÉFONO 2 :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 335, -1, -1));
        add(txtNroTelefono1Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 357, 320, 40));
        add(txtNroTelefono2Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 357, 320, 40));

        jLabel9.setText("CORREO :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 415, -1, -1));
        add(txtEmailEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 437, 687, 40));

        jLabel10.setText("CARGO :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 495, -1, -1));

        txtCargoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "ADMIN", "USUARIO" }));
        add(txtCargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 517, 320, 40));

        jLabel11.setText("FECHA NACIMIENTO :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 495, -1, -1));
        add(txtFNacimientoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 517, 321, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/salvar.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        actualizarEmpleado();
        limpiarCajas();
    }//GEN-LAST:event_btnGuardarMouseClicked
    
    public void cargarEmpelado(String nroDocumento) {        
        
        daoEmpleados empleadoDatos = new daoEmpleados();        
        empleado objEmpleado = empleadoDatos.buscarEmpleadoXnroDocumento(nroDocumento);
        txtNroDocEmpleado.setEnabled(false);
        
        txtNombreEmpleado.setText(objEmpleado.getNombre());
        txtApePatEmpleado.setText(objEmpleado.getApellidoPat());
        txtApeMatEmpleado.setText(objEmpleado.getApellidoMat());
        txtTipoDocEmpleado.setSelectedItem(objEmpleado.getTipoDocumento());            
        txtNroDocEmpleado.setText(objEmpleado.getNumeroDocumento());
        txtNroTelefono1Empleado.setText(objEmpleado.getNroTelefono1());
        txtNroTelefono2Empleado.setText(objEmpleado.getNroTelefono2());
        txtEmailEmpleado.setText(objEmpleado.getEmail());
        txtCargoEmpleado.setSelectedItem(objEmpleado.getCargo());
        //txtFNacimientoEmpleado.setText(objEmpleado.getFechaNacimiento().toString());
    }
    
    private void actualizarEmpleado() {        
        empleado objEmpleado = new empleado();
        daoEmpleados empleadoDatos = new daoEmpleados();
        String msjRespuesta;
        
        objEmpleado.setNombre(txtNombreEmpleado.getText());
        objEmpleado.setApellidoPat(txtApePatEmpleado.getText());
        objEmpleado.setApellidoMat(txtApeMatEmpleado.getText());
        objEmpleado.setTipoDocumento(txtTipoDocEmpleado.getSelectedItem().toString());
        objEmpleado.setCargo(txtCargoEmpleado.getSelectedItem().toString());
        objEmpleado.setEmail(txtEmailEmpleado.getText());
        //objEmpleado.setFechaNacimiento(fNacimiento);           
        objEmpleado.setNumeroDocumento(txtNroDocEmpleado.getText());
        objEmpleado.setNroTelefono1(txtNroTelefono1Empleado.getText());
        objEmpleado.setNroTelefono2(txtNroTelefono2Empleado.getText());
        
        msjRespuesta = empleadoDatos.actualizarEmpleado(objEmpleado);
        JOptionPane.showMessageDialog(this, msjRespuesta);
    }
    
    private void limpiarCajas() {
        JTextField caja;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)this.getComponent(i);
                caja.setText(null);
            }
        }
        
        JComboBox combo;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JComboBox")) {
                combo = (JComboBox)this.getComponent(i);
                combo.setSelectedIndex(0);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApeMatEmpleado;
    private javax.swing.JTextField txtApePatEmpleado;
    private javax.swing.JComboBox<String> txtCargoEmpleado;
    private javax.swing.JTextField txtEmailEmpleado;
    private javax.swing.JFormattedTextField txtFNacimientoEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNroDocEmpleado;
    private javax.swing.JTextField txtNroTelefono1Empleado;
    private javax.swing.JTextField txtNroTelefono2Empleado;
    private javax.swing.JComboBox<String> txtTipoDocEmpleado;
    // End of variables declaration//GEN-END:variables
}
