/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.recarga;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import utp.edu.pe.dao.daoCarnes;
import static utp.edu.pe.app.frmPrincipal.content;
import utp.edu.pe.dao.daoTarjetas;
import utp.edu.pe.entity.Tarjeta;
import java.util.List;
import javax.swing.JOptionPane;
import utp.edu.pe.entity.Carne;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class crearCarne extends javax.swing.JPanel {

    /**
     * Creates new form crearCarne
     */
    
    static List<Tarjeta> lstTarjetas = new ArrayList();
    
    public crearCarne() {        
        initComponents();
        cargarTarjetas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtNroCarne = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JLabel();
        txtNroDocumento = new javax.swing.JLabel();
        generarNroCarne = new javax.swing.JLabel();
        txtMontoPasaje = new javax.swing.JTextField();
        cboTipoTarjeta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSaldoCarne = new javax.swing.JTextField();
        recuperarSaldo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));
        setPreferredSize(new java.awt.Dimension(770, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Crear Carne");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setText("NRO CARNE:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 95, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 758, 10));

        jLabel3.setText("TIPO TARJETA:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 175, -1, -1));

        txtNroCarne.setEnabled(false);
        add(txtNroCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 117, 620, 40));

        jLabel4.setText("MONTO PASAJE:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 175, -1, -1));

        jLabel9.setText("DESCRIPCION :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 687, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/salvar.png"))); // NOI18N
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, -1));

        txtNroDocumento.setText("txtNroDocumento");
        add(txtNroDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        generarNroCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/boton-actualizar.png"))); // NOI18N
        generarNroCarne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generarNroCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarNroCarneMouseClicked(evt);
            }
        });
        add(generarNroCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));
        add(txtMontoPasaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 320, 40));

        cboTipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cboTipoTarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoTarjetaItemStateChanged(evt);
            }
        });
        add(cboTipoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, 40));

        jLabel5.setText("RECUPERAR SALDO POR SINIESTRO: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txtSaldoCarne.setEnabled(false);
        add(txtSaldoCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 610, 40));

        recuperarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/recuperarse.png"))); // NOI18N
        recuperarSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recuperarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recuperarSaldoMouseClicked(evt);
            }
        });
        add(recuperarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        crearCarne();
        limpiarCajas();
        
        mainRecarga mainRecarga = new mainRecarga();
        mainRecarga.setSize(770, 700);
        mainRecarga.setLocation(0,0);
        
        mainRecarga.buscarPasajero(txtNroDocumento.getText());
        
        content.removeAll();
        content.add(mainRecarga, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void generarNroCarneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarNroCarneMouseClicked
        generarCarne();
    }//GEN-LAST:event_generarNroCarneMouseClicked

    private void cboTipoTarjetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoTarjetaItemStateChanged
        
        int index = cboTipoTarjeta.getSelectedIndex();
        
        if (index<1) {
            txtMontoPasaje.setText("");
            txtDescripcion.setText("");
        } else {
            txtMontoPasaje.setText(String.valueOf(lstTarjetas.get(cboTipoTarjeta.getSelectedIndex()-1).getMontoPasaje()));
            txtDescripcion.setText(String.valueOf(lstTarjetas.get(cboTipoTarjeta.getSelectedIndex()-1).getDescripcion()));
        }        
    }//GEN-LAST:event_cboTipoTarjetaItemStateChanged

    private void recuperarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperarSaldoMouseClicked
        recuperarSaldoSiniestro();
    }//GEN-LAST:event_recuperarSaldoMouseClicked
    
    private void recuperarSaldoSiniestro() {
        daoCarnes carneDatos = new daoCarnes();
        Float ultimoSaldo = carneDatos.recuperarSaldoSiniestro(txtNroDocumento.getText(), cboTipoTarjeta.getSelectedIndex());
        
        txtSaldoCarne.setText(String.valueOf(ultimoSaldo));
    }
    
    public void crearCarne() {        
        Carne objCarne = new Carne();
        daoCarnes carneDatos = new daoCarnes();
        String msjRespuesta;
        
        objCarne.setNroCarne(Integer.valueOf(txtNroCarne.getText()));
        objCarne.setNumeroDocumento(txtNroDocumento.getText());
        objCarne.setIdTarjeta(cboTipoTarjeta.getSelectedIndex());
        objCarne.setSaldo(Float.valueOf(txtSaldoCarne.getText()));
        
        msjRespuesta = carneDatos.crearCarne(objCarne);
        JOptionPane.showMessageDialog(this, msjRespuesta);
    }
    
    public void generarCarne() {
        daoCarnes carneDatos = new daoCarnes();        
        int nroCarne = carneDatos.generarCarne();
        String nroCarneFormat = String.format("%0" + 15 + "d", nroCarne);
        
        txtNroCarne.setText(nroCarneFormat);
    }
    
    public void cargarDocumento(String nroDocumento) {        
        
        txtNroDocumento.setVisible(false);
        txtNroDocumento.setText(nroDocumento);
        
    }
    
    private void cargarTarjetas() {
        daoTarjetas tarjetaDatos = new daoTarjetas();
        lstTarjetas = tarjetaDatos.listaTarjetas();
        
        for (int i=0;i<lstTarjetas.size();i++) {            
            cboTipoTarjeta.addItem(lstTarjetas.get(i).getServicio());            
        }
    }
    
    private void limpiarCajas() {
        JTextField caja;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)this.getComponent(i);
                caja.setText(null);
            }
        }
        
        JComboBox combo;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JComboBox")) {
                combo = (JComboBox)this.getComponent(i);
                combo.setSelectedIndex(0);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JComboBox<String> cboTipoTarjeta;
    private javax.swing.JLabel generarNroCarne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel recuperarSaldo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMontoPasaje;
    private javax.swing.JTextField txtNroCarne;
    private javax.swing.JLabel txtNroDocumento;
    private javax.swing.JTextField txtSaldoCarne;
    // End of variables declaration//GEN-END:variables
}
