/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.recarga;

import utp.edu.pe.app.empleado.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import static utp.edu.pe.app.frmPrincipal.content;
import utp.edu.pe.dao.daoCarnes;
import utp.edu.pe.entity.carne;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class mainRecarga extends javax.swing.JPanel {

    /**
     * Creates new form listarEmpleado
     */
    public mainRecarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarnes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPasajero = new javax.swing.JTextField();
        btnBuscarPasajero = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnRecargar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));

        tblCarnes.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblCarnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Documento", "Pasajero", "Descripcion", "NroCarne", "SaldoActual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCarnes.getTableHeader().setReorderingAllowed(false);
        tblCarnes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarnesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCarnes);
        if (tblCarnes.getColumnModel().getColumnCount() > 0) {
            tblCarnes.getColumnModel().getColumn(0).setResizable(false);
            tblCarnes.getColumnModel().getColumn(1).setResizable(false);
            tblCarnes.getColumnModel().getColumn(2).setResizable(false);
            tblCarnes.getColumnModel().getColumn(3).setResizable(false);
            tblCarnes.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Carne de pasajeros");

        txtBuscarPasajero.setText("Ingrese el numero de documento del pasajero a buscar");
        txtBuscarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarPasajeroMouseClicked(evt);
            }
        });

        btnBuscarPasajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/lupa.png"))); // NOI18N
        btnBuscarPasajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPasajeroMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRecargar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("RECARGAR");
        btnRecargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecargarMouseClicked(evt);
            }
        });
        jPanel1.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtBuscarPasajero)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarPasajero)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarPasajeroMouseClicked
        if (txtBuscarPasajero.getText().equals("Ingrese el numero de documento del pasajero a buscar")){
            txtBuscarPasajero.setText("");
            txtBuscarPasajero.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBuscarPasajeroMouseClicked

    private void btnBuscarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPasajeroMouseClicked
        DefaultTableModel modeloTabla = (DefaultTableModel) tblCarnes.getModel();
        modeloTabla.setRowCount(0);
        daoCarnes carneDatos = new daoCarnes();
        List<carne> lstCarnes = carneDatos.buscarCarnesXnroDocumento(txtBuscarPasajero.getText());        
        String datos[] = new String[5];
        
        for (int i=0;i<lstCarnes.size();i++) {
            datos[0] = lstCarnes.get(i).getNumeroDocumento();
            datos[1] = lstCarnes.get(i).getPasajero();            
            datos[2] = lstCarnes.get(i).getDescripcionTarjeta();
            datos[3] = lstCarnes.get(i).getNroCarne().toString();
            datos[4] = lstCarnes.get(i).getSaldo().toString();
            modeloTabla.addRow(datos);
        }
    }//GEN-LAST:event_btnBuscarPasajeroMouseClicked

    private void tblCarnesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarnesMouseClicked
        if (txtBuscarPasajero.getText().equals("")) {
            txtBuscarPasajero.setText("Ingrese el numero de documento del pasajero a buscar");
            txtBuscarPasajero.setForeground(Color.BLACK);
        }        
    }//GEN-LAST:event_tblCarnesMouseClicked

    private void btnRecargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecargarMouseClicked
        recargarCarne recargarCarne = new recargarCarne();
        recargarCarne.setSize(770, 700);
        recargarCarne.setLocation(0,0);
        
        int fila = tblCarnes.getSelectedRow();
        int nroCarne = Integer.parseInt(tblCarnes.getValueAt(fila, 3).toString());        
        
        recargarCarne.cargarCarne(nroCarne);
        
        content.removeAll();
        content.add(recargarCarne, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnRecargarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarPasajero;
    private javax.swing.JLabel btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblCarnes;
    private javax.swing.JTextField txtBuscarPasajero;
    // End of variables declaration//GEN-END:variables
}
