/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.recarga;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static utp.edu.pe.app.frmPrincipal.content;
import static utp.edu.pe.app.frmPrincipal.lblRol;
import utp.edu.pe.dao.daoCarnes;
import utp.edu.pe.entity.Carne;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class mainRecarga extends javax.swing.JPanel {

    /**
     * Creates new form listarEmpleado
     */
    static Boolean rolPasajero = lblRol.getText().equals("PASAJERO");
    
    public mainRecarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarnes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPasajero = new javax.swing.JTextField();
        btnBuscarPasajero = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnRecargar = new javax.swing.JLabel();
        panelCrearCarne = new javax.swing.JPanel();
        btnCrearCarne = new javax.swing.JLabel();
        panelSiniestro = new javax.swing.JPanel();
        btnSiniestro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));

        tblCarnes.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblCarnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Pasajero", "Descripcion", "NroCarne", "SaldoActual", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCarnes.getTableHeader().setReorderingAllowed(false);
        tblCarnes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarnesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCarnes);
        if (tblCarnes.getColumnModel().getColumnCount() > 0) {
            tblCarnes.getColumnModel().getColumn(0).setResizable(false);
            tblCarnes.getColumnModel().getColumn(1).setResizable(false);
            tblCarnes.getColumnModel().getColumn(2).setResizable(false);
            tblCarnes.getColumnModel().getColumn(3).setResizable(false);
            tblCarnes.getColumnModel().getColumn(4).setResizable(false);
            tblCarnes.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Carne de pasajeros");

        txtBuscarPasajero.setText("Ingrese el numero de documento del pasajero a buscar");
        txtBuscarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarPasajeroMouseClicked(evt);
            }
        });

        btnBuscarPasajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/lupa.png"))); // NOI18N
        btnBuscarPasajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPasajeroMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));

        btnRecargar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("RECARGAR");
        btnRecargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecargarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRecargar)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRecargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCrearCarne.setBackground(new java.awt.Color(0, 102, 204));
        panelCrearCarne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCrearCarne.setMaximumSize(new java.awt.Dimension(100, 40));
        panelCrearCarne.setMinimumSize(new java.awt.Dimension(100, 40));
        panelCrearCarne.setPreferredSize(new java.awt.Dimension(100, 40));

        btnCrearCarne.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnCrearCarne.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCarne.setText("CREAR CARNE");
        btnCrearCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCarneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearCarneLayout = new javax.swing.GroupLayout(panelCrearCarne);
        panelCrearCarne.setLayout(panelCrearCarneLayout);
        panelCrearCarneLayout.setHorizontalGroup(
            panelCrearCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearCarneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCrearCarneLayout.setVerticalGroup(
            panelCrearCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearCarneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearCarne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSiniestro.setBackground(new java.awt.Color(255, 0, 51));
        panelSiniestro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSiniestro.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnSiniestro.setForeground(new java.awt.Color(255, 255, 255));
        btnSiniestro.setText("SINIESTRO");
        btnSiniestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiniestroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSiniestroLayout = new javax.swing.GroupLayout(panelSiniestro);
        panelSiniestro.setLayout(panelSiniestroLayout);
        panelSiniestroLayout.setHorizontalGroup(
            panelSiniestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSiniestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSiniestro, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSiniestroLayout.setVerticalGroup(
            panelSiniestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSiniestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSiniestro, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtBuscarPasajero)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarPasajero)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panelCrearCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelSiniestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCrearCarne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSiniestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarPasajeroMouseClicked
        if (txtBuscarPasajero.getText().equals("Ingrese el numero de documento del pasajero a buscar")){
            txtBuscarPasajero.setText("");
            txtBuscarPasajero.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBuscarPasajeroMouseClicked

    private void btnBuscarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPasajeroMouseClicked
        buscarPasajero("");
    }//GEN-LAST:event_btnBuscarPasajeroMouseClicked

    private void tblCarnesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarnesMouseClicked
        if (txtBuscarPasajero.getText().equals("")) {
            txtBuscarPasajero.setText("Ingrese el numero de documento del pasajero a buscar");
            txtBuscarPasajero.setForeground(Color.BLACK);
        }        
    }//GEN-LAST:event_tblCarnesMouseClicked

    public void buscarPasajero(String nroDocumento) {
        if (nroDocumento.length()>=1) {
            txtBuscarPasajero.setText(nroDocumento);
            txtBuscarPasajero.setEnabled(!rolPasajero);
            DefaultTableModel modeloTabla = (DefaultTableModel) tblCarnes.getModel();
            modeloTabla.setRowCount(0);
            daoCarnes carneDatos = new daoCarnes();
            List<Carne> lstCarnes = carneDatos.buscarCarnesXnroDocumento(nroDocumento);        
            String datos[] = new String[6];
        
            for (int i=0;i<lstCarnes.size();i++) {
                datos[0] = lstCarnes.get(i).getNumeroDocumento();
                datos[1] = lstCarnes.get(i).getPasajero();            
                datos[2] = lstCarnes.get(i).getDescripcionTarjeta();
                datos[3] = lstCarnes.get(i).getNroCarne().toString();
                datos[4] = lstCarnes.get(i).getSaldo().toString();
                datos[5] = lstCarnes.get(i).getEstado();
                modeloTabla.addRow(datos);
            }
        } else {
            DefaultTableModel modeloTabla = (DefaultTableModel) tblCarnes.getModel();
            modeloTabla.setRowCount(0);
            daoCarnes carneDatos = new daoCarnes();
            List<Carne> lstCarnes = carneDatos.buscarCarnesXnroDocumento(txtBuscarPasajero.getText());        
            String datos[] = new String[6];
        
            for (int i=0;i<lstCarnes.size();i++) {
                datos[0] = lstCarnes.get(i).getNumeroDocumento();
                datos[1] = lstCarnes.get(i).getPasajero();            
                datos[2] = lstCarnes.get(i).getDescripcionTarjeta();
                datos[3] = lstCarnes.get(i).getNroCarne().toString();
                datos[4] = lstCarnes.get(i).getSaldo().toString();
                datos[5] = lstCarnes.get(i).getEstado();
                modeloTabla.addRow(datos);
            }
        }
        
        if(rolPasajero){
            panelCrearCarne.setVisible(false);
            panelSiniestro.setVisible(false);
        }
    }
    
    private void btnRecargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecargarMouseClicked
        recargarCarne recargarCarne = new recargarCarne();
        recargarCarne.setSize(770, 700);
        recargarCarne.setLocation(0,0);
        
        int fila = tblCarnes.getSelectedRow();
        int nroCarne = Integer.parseInt(tblCarnes.getValueAt(fila, 3).toString());        
        
        if (nroCarne < 1 ) {
            JOptionPane.showMessageDialog(this, "EL PASAJERO NO TIENE CARNET");        
        } else {        
            recargarCarne.cargarCarne(nroCarne, txtBuscarPasajero.getText());
            content.removeAll();
            content.add(recargarCarne, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
        }
    }//GEN-LAST:event_btnRecargarMouseClicked

    private void btnCrearCarneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCarneMouseClicked
        crearCarne crearCarne = new crearCarne();
        crearCarne.setSize(770, 700);
        crearCarne.setLocation(0,0);
        
        int fila = tblCarnes.getSelectedRow();
        
        if(fila < 0) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN PASAJERO");        
        } else {
            String nroDocumento = tblCarnes.getValueAt(fila, 0).toString();

            crearCarne.cargarDocumento(nroDocumento);
            content.removeAll();
            content.add(crearCarne, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
        }
              
    }//GEN-LAST:event_btnCrearCarneMouseClicked

    private void btnSiniestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiniestroMouseClicked
        siniestroCarne siniestroCarne = new siniestroCarne();
        siniestroCarne.setSize(770, 700);
        siniestroCarne.setLocation(0,0);
        
        int fila = tblCarnes.getSelectedRow();
        int nroCarne = Integer.parseInt(tblCarnes.getValueAt(fila, 3).toString());        
        
        if (nroCarne < 1 ) {
            JOptionPane.showMessageDialog(this, "EL PASAJERO NO TIENE CARNET");        
        } else {        
            siniestroCarne.cargarCarne(nroCarne, txtBuscarPasajero.getText());
            content.removeAll();
            content.add(siniestroCarne, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
        }
    }//GEN-LAST:event_btnSiniestroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarPasajero;
    private javax.swing.JLabel btnCrearCarne;
    private javax.swing.JLabel btnRecargar;
    private javax.swing.JLabel btnSiniestro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelCrearCarne;
    private javax.swing.JPanel panelSiniestro;
    private javax.swing.JTable tblCarnes;
    private javax.swing.JTextField txtBuscarPasajero;
    // End of variables declaration//GEN-END:variables
}
