/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.pasajero;

import java.awt.BorderLayout;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static utp.edu.pe.app.frmPrincipal.content;
import utp.edu.pe.dao.daoPasajeros;
import utp.edu.pe.entity.Pasajero;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class actualizarPasajero extends javax.swing.JPanel {

    /**
     * Creates new form actualizarPasajero
     */
    public actualizarPasajero() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtNombrePasajero = new javax.swing.JTextField();
        txtApePatPasajero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApeMatPasajero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNroDocPasajero = new javax.swing.JTextField();
        txtTipoDocPasajero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNroTelefono1Pasajero = new javax.swing.JTextField();
        txtNroTelefono2Pasajero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmailPasajero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEstudiantePasajero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtFNacimientoPasajero = new javax.swing.JFormattedTextField();
        btnGuardar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));
        setPreferredSize(new java.awt.Dimension(770, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Actualizar pasajero");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setText("NOMBRE :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 95, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 758, 10));

        jLabel3.setText("APELLIDO PATERNO :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 175, -1, -1));
        add(txtNombrePasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 117, 687, 40));
        add(txtApePatPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 197, 320, 40));

        jLabel4.setText("APELLIDO MATERNO :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 175, -1, -1));
        add(txtApeMatPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 197, 320, 40));

        jLabel5.setText("TIPO DOCUMENTO :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 255, -1, -1));

        jLabel6.setText("NÚMERO DOCUMENTO :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 255, -1, -1));
        add(txtNroDocPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 277, 320, 40));

        txtTipoDocPasajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "DNI", "RUC", "CE" }));
        add(txtTipoDocPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 277, 320, 40));

        jLabel7.setText("TELÉFONO 1 :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 335, -1, -1));

        jLabel8.setText("TELÉFONO 2 :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 335, -1, -1));
        add(txtNroTelefono1Pasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 357, 320, 40));
        add(txtNroTelefono2Pasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 357, 320, 40));

        jLabel9.setText("CORREO :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 415, -1, -1));
        add(txtEmailPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 437, 687, 40));

        jLabel10.setText("ESTUDIANTE :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 495, -1, -1));

        txtEstudiantePasajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "SI", "NO" }));
        add(txtEstudiantePasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 517, 320, 40));

        jLabel11.setText("FECHA NACIMIENTO :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 495, -1, -1));
        add(txtFNacimientoPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 517, 321, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/salvar.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        actualizarPasajero();
        limpiarCajas();
        
        mainPasajero mainPasajero = new mainPasajero();
        mainPasajero.setSize(770, 700);
        mainPasajero.setLocation(0,0);
        
        content.removeAll();
        content.add(mainPasajero, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnGuardarMouseClicked
    
    public void cargarPasajero(String nroDocumento) {                
        
        daoPasajeros pasajeroDatos = new daoPasajeros();
        Pasajero objPasajero = pasajeroDatos.buscarPasajeroXnroDocumento(nroDocumento);
        txtNroDocPasajero.setEnabled(false);
        
        txtNombrePasajero.setText(objPasajero.getNombre());
        txtApePatPasajero.setText(objPasajero.getApellidoPat());
        txtApeMatPasajero.setText(objPasajero.getApellidoMat());
        txtTipoDocPasajero.setSelectedItem(objPasajero.getTipoDocumento());            
        txtNroDocPasajero.setText(objPasajero.getNumeroDocumento());
        txtNroTelefono1Pasajero.setText(objPasajero.getNroTelefono1());
        txtNroTelefono2Pasajero.setText(objPasajero.getNroTelefono2());
        txtEmailPasajero.setText(objPasajero.getEmail());
        txtEstudiantePasajero.setSelectedItem(objPasajero.getEstudiante());
        //txtFNacimientoEmpleado.setText(objEmpleado.getFechaNacimiento().toString());
    }
    
    private void actualizarPasajero() {        
        Pasajero objPasajero = new Pasajero();
        daoPasajeros pasajeroDatos = new daoPasajeros();
        String msjRespuesta;
        
        objPasajero.setNombre(txtNombrePasajero.getText());
        objPasajero.setApellidoPat(txtApePatPasajero.getText());
        objPasajero.setApellidoMat(txtApeMatPasajero.getText());
        objPasajero.setTipoDocumento(txtTipoDocPasajero.getSelectedItem().toString());
        objPasajero.setEstudiante(txtEstudiantePasajero.getSelectedItem().toString());
        objPasajero.setEmail(txtEmailPasajero.getText());
        //objEmpleado.setFechaNacimiento(fNacimiento);           
        objPasajero.setNumeroDocumento(txtNroDocPasajero.getText());
        objPasajero.setNroTelefono1(txtNroTelefono1Pasajero.getText());
        objPasajero.setNroTelefono2(txtNroTelefono2Pasajero.getText());
        
        msjRespuesta = pasajeroDatos.actualizarPasajero(objPasajero);
        JOptionPane.showMessageDialog(this, msjRespuesta);
    }
    
    private void limpiarCajas() {
        JTextField caja;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)this.getComponent(i);
                caja.setText(null);
            }
        }
        
        JComboBox combo;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JComboBox")) {
                combo = (JComboBox)this.getComponent(i);
                combo.setSelectedIndex(0);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApeMatPasajero;
    private javax.swing.JTextField txtApePatPasajero;
    private javax.swing.JTextField txtEmailPasajero;
    private javax.swing.JComboBox<String> txtEstudiantePasajero;
    private javax.swing.JFormattedTextField txtFNacimientoPasajero;
    private javax.swing.JTextField txtNombrePasajero;
    private javax.swing.JTextField txtNroDocPasajero;
    private javax.swing.JTextField txtNroTelefono1Pasajero;
    private javax.swing.JTextField txtNroTelefono2Pasajero;
    private javax.swing.JComboBox<String> txtTipoDocPasajero;
    // End of variables declaration//GEN-END:variables
}
