/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.pasajero;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static utp.edu.pe.app.frmPrincipal.content;
import utp.edu.pe.dao.daoPasajeros;
import utp.edu.pe.entity.Pasajero;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class mainPasajero extends javax.swing.JPanel {

    /**
     * Creates new form mainPasajero
     */
    public mainPasajero() {
        initComponents();
        cargarPasajeros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasajeros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPasajero = new javax.swing.JTextField();
        btnBuscarPasajero = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnNuevoPasajero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnActualizarPasajero = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEliminarPasajero = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));

        tblPasajeros.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Documento", "Telefono", "Estudiante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPasajeros.getTableHeader().setReorderingAllowed(false);
        tblPasajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasajerosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPasajeros);
        if (tblPasajeros.getColumnModel().getColumnCount() > 0) {
            tblPasajeros.getColumnModel().getColumn(0).setResizable(false);
            tblPasajeros.getColumnModel().getColumn(1).setResizable(false);
            tblPasajeros.getColumnModel().getColumn(2).setResizable(false);
            tblPasajeros.getColumnModel().getColumn(3).setResizable(false);
            tblPasajeros.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Pasajeros");

        txtBuscarPasajero.setText("Ingrese el nombre de pasajero a buscar");
        txtBuscarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarPasajeroMouseClicked(evt);
            }
        });

        btnBuscarPasajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/lupa.png"))); // NOI18N
        btnBuscarPasajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPasajeroMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoPasajero.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnNuevoPasajero.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoPasajero.setText("NUEVO");
        btnNuevoPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoPasajeroMouseClicked(evt);
            }
        });
        jPanel1.add(btnNuevoPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizarPasajero.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnActualizarPasajero.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarPasajero.setText("ACTUALIZAR");
        btnActualizarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPasajeroMouseClicked(evt);
            }
        });
        jPanel2.add(btnActualizarPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarPasajero.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnEliminarPasajero.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPasajero.setText("ELIMINAR");
        btnEliminarPasajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPasajeroMouseClicked(evt);
            }
        });
        jPanel3.add(btnEliminarPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtBuscarPasajero)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarPasajero)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarPasajeroMouseClicked
        if (txtBuscarPasajero.getText().equals("Ingrese el nombre de pasajero a buscar")){
            txtBuscarPasajero.setText("");
            txtBuscarPasajero.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBuscarPasajeroMouseClicked

    private void btnBuscarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPasajeroMouseClicked
        DefaultTableModel modeloTabla = (DefaultTableModel) tblPasajeros.getModel();
        modeloTabla.setRowCount(0);
        daoPasajeros pasajeroDatos = new daoPasajeros();
        List<Pasajero> lstPasajeros = pasajeroDatos.buscarPasajeros(txtBuscarPasajero.getText());
        String datos[] = new String[5];
        
        for (int i=0;i<lstPasajeros.size();i++) {
            datos[0] = lstPasajeros.get(i).getNombre();
            datos[1] = lstPasajeros.get(i).getApellidoPat() + " " + lstPasajeros.get(i).getApellidoMat();            
            datos[2] = lstPasajeros.get(i).getNumeroDocumento();
            datos[3] = lstPasajeros.get(i).getNroTelefono1();
            datos[4] = lstPasajeros.get(i).getEstudiante();
            modeloTabla.addRow(datos);
        }
    }//GEN-LAST:event_btnBuscarPasajeroMouseClicked

    private void tblPasajerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasajerosMouseClicked
        if (txtBuscarPasajero.getText().equals("")) {
            txtBuscarPasajero.setText("Ingrese el nombre de pasajero a buscar");
            txtBuscarPasajero.setForeground(Color.BLACK);
        }        
    }//GEN-LAST:event_tblPasajerosMouseClicked

    private void btnNuevoPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPasajeroMouseClicked
        crearPasajero crearPasajero = new crearPasajero();
        crearPasajero.setSize(770, 700);
        crearPasajero.setLocation(0,0);
        
        content.removeAll();
        content.add(crearPasajero, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();        
    }//GEN-LAST:event_btnNuevoPasajeroMouseClicked

    private void btnActualizarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPasajeroMouseClicked
        actualizarPasajero actualizarPasajero = new actualizarPasajero();
        actualizarPasajero.setSize(770, 700);
        actualizarPasajero.setLocation(0,0);
        
        int fila = tblPasajeros.getSelectedRow();
        String nroDocumento = tblPasajeros.getValueAt(fila, 2).toString();        
        actualizarPasajero.cargarPasajero(nroDocumento);
        
        content.removeAll();
        content.add(actualizarPasajero, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnActualizarPasajeroMouseClicked

    private void btnEliminarPasajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPasajeroMouseClicked
        daoPasajeros pasajeroDatos = new daoPasajeros();
        int fila = tblPasajeros.getSelectedRow();
        String msjRespuesta;        
        String nroDocumento = tblPasajeros.getValueAt(fila, 2).toString();        
        int res;
        
        res = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el registro seleccionado", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (res == 0) {
            msjRespuesta = pasajeroDatos.eliminarPasajero(nroDocumento);
            JOptionPane.showMessageDialog(this, msjRespuesta);
            cargarPasajeros();
        }        
    }//GEN-LAST:event_btnEliminarPasajeroMouseClicked
    
    public void cargarPasajeros() {                
        DefaultTableModel modeloTabla = (DefaultTableModel) tblPasajeros.getModel();
        modeloTabla.setRowCount(0);
        
        daoPasajeros pasajeroDatos = new daoPasajeros();
        List<Pasajero> lstPasajeros = pasajeroDatos.listarPasajeros();
        String datos[] = new String[5];
        
        for (int i=0;i<lstPasajeros.size();i++) {
            datos[0] = lstPasajeros.get(i).getNombre();
            datos[1] = lstPasajeros.get(i).getApellidoPat() + " " + lstPasajeros.get(i).getApellidoMat();            
            datos[2] = lstPasajeros.get(i).getNumeroDocumento();
            datos[3] = lstPasajeros.get(i).getNroTelefono1();
            datos[4] = lstPasajeros.get(i).getEstudiante();
            modeloTabla.addRow(datos);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActualizarPasajero;
    private javax.swing.JLabel btnBuscarPasajero;
    private javax.swing.JLabel btnEliminarPasajero;
    private javax.swing.JLabel btnNuevoPasajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblPasajeros;
    private javax.swing.JTextField txtBuscarPasajero;
    // End of variables declaration//GEN-END:variables
}
