/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utp.edu.pe.app.usuario;

import java.awt.Color;
import javax.swing.JOptionPane;
import utp.edu.pe.app.frmPrincipal;
import utp.edu.pe.dao.daoUsuarios;
import utp.edu.pe.entity.Usuario;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class frmAcceso extends javax.swing.JFrame {

    /**
     * Creates new form frmAcceso
     */
    public frmAcceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPrincipal = new javax.swing.JPanel();
        bgTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        separator1 = new javax.swing.JSeparator();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        separator2 = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        bgPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        bgPrincipal.setPreferredSize(new java.awt.Dimension(600, 500));
        bgPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgTitulo.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISGETAR");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/pago.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout bgTituloLayout = new javax.swing.GroupLayout(bgTitulo);
        bgTitulo.setLayout(bgTituloLayout);
        bgTituloLayout.setHorizontalGroup(
            bgTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgTituloLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
        bgTituloLayout.setVerticalGroup(
            bgTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgTituloLayout.createSequentialGroup()
                .addGroup(bgTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgTituloLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(bgTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(bgTituloLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        bgPrincipal.add(bgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 170));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblUsuario.setText("USUARIO");
        bgPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Ingrese su usuario aqui");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        bgPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 360, 30));
        bgPrincipal.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 370, 20));

        lblContrasena.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblContrasena.setText("CONTRASEÑA");
        bgPrincipal.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        txtContrasena.setForeground(new java.awt.Color(153, 153, 153));
        txtContrasena.setText("123456789");
        txtContrasena.setBorder(null);
        txtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContrasenaMouseClicked(evt);
            }
        });
        bgPrincipal.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 360, 30));
        bgPrincipal.add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 370, 10));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/ingresar.png"))); // NOI18N
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        bgPrincipal.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        validarUsuario();
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        if (txtUsuario.getText().equals("Ingrese su usuario aqui")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.BLACK);
        }
        
        if (String.valueOf(txtContrasena.getPassword()).isEmpty()) {
            txtContrasena.setText("123456789");
            txtContrasena.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasenaMouseClicked
        if (String.valueOf(txtContrasena.getPassword()).equals("123456789")) {
            txtContrasena.setText("");
            txtContrasena.setForeground(Color.BLACK);
        }
        
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Ingrese su usuario aqui");
            txtUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtContrasenaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAcceso().setVisible(true);
            }
        });
    }
    
    public void validarUsuario() {
        Usuario objUsuario = new Usuario();
        daoUsuarios usuarioDatos = new daoUsuarios();
        
        objUsuario.setUsuario(txtUsuario.getText());
        objUsuario.setPassword(String.valueOf(txtContrasena.getPassword()));        
        objUsuario = usuarioDatos.validarUsuario(objUsuario);
        if (objUsuario.getEstado()){
            JOptionPane.showMessageDialog(this, "BIENVENIDO");
            frmPrincipal frmPrincipal = new frmPrincipal();
            frmPrincipal.cargarPerfil(objUsuario);
            frmPrincipal.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ACCESO DENEGADO");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPrincipal;
    private javax.swing.JPanel bgTitulo;
    private javax.swing.JLabel btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
