/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.usuario;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static utp.edu.pe.app.frmPrincipal.lblRol;
import static utp.edu.pe.app.frmPrincipal.lblNroDoc;
import utp.edu.pe.dao.daoUsuarios;
import utp.edu.pe.entity.Usuario;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class mainUsuario extends javax.swing.JPanel {

    /**
     * Creates new form mainUsuario
     */
    static Boolean rolPasajero = lblRol.getText().equals("PASAJERO");
    
    public mainUsuario() {
        initComponents();
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelActualizar = new javax.swing.JPanel();
        btnActualzarPass = new javax.swing.JLabel();
        panelRestaurar = new javax.swing.JPanel();
        btnRestaurarPass = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));

        tblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Documento", "Usuario", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tblUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tblUsuarios.getColumnModel().getColumn(2).setResizable(false);
            tblUsuarios.getColumnModel().getColumn(3).setResizable(false);
            tblUsuarios.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Empleados");

        panelActualizar.setBackground(new java.awt.Color(0, 102, 204));
        panelActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelActualizar.setLayout(new java.awt.BorderLayout());

        btnActualzarPass.setFont(new java.awt.Font("Roboto Light", 1, 10)); // NOI18N
        btnActualzarPass.setForeground(new java.awt.Color(255, 255, 255));
        btnActualzarPass.setText("Cambiar contraseña");
        btnActualzarPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualzarPassMouseClicked(evt);
            }
        });
        panelActualizar.add(btnActualzarPass, java.awt.BorderLayout.CENTER);

        panelRestaurar.setBackground(new java.awt.Color(0, 153, 0));
        panelRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRestaurar.setLayout(new java.awt.BorderLayout());

        btnRestaurarPass.setFont(new java.awt.Font("Roboto Light", 1, 10)); // NOI18N
        btnRestaurarPass.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurarPass.setText("Restaurar contraseña");
        btnRestaurarPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestaurarPassMouseClicked(evt);
            }
        });
        panelRestaurar.add(btnRestaurarPass, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 540, Short.MAX_VALUE)
                        .addComponent(panelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRestaurar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurarPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarPassMouseClicked
        daoUsuarios usuarioDatos = new daoUsuarios();
        String msjRespuesta;
        
        int fila = tblUsuarios.getSelectedRow();
        String usuario = tblUsuarios.getValueAt(fila, 3).toString();
        
        int res;        
        res = JOptionPane.showConfirmDialog(this, "¿Desea restaurar la contraseña del usuario " + usuario + " ?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (res == 0) {
            msjRespuesta = usuarioDatos.restaurarUsuario(usuario);
            JOptionPane.showMessageDialog(this, msjRespuesta);        
        }
        
    }//GEN-LAST:event_btnRestaurarPassMouseClicked

    private void btnActualzarPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualzarPassMouseClicked
        daoUsuarios usuarioDatos = new daoUsuarios();
        String msjRespuesta;
        
        int fila = tblUsuarios.getSelectedRow();
        String usuario = tblUsuarios.getValueAt(fila, 3).toString();
        
        String pass;        
        pass = JOptionPane.showInputDialog(this, "Ingrese su nueva contraseña", "Password", JOptionPane.YES_OPTION);
        
        msjRespuesta = usuarioDatos.cambiarPass(usuario,pass);
        JOptionPane.showMessageDialog(this, msjRespuesta);
        
    }//GEN-LAST:event_btnActualzarPassMouseClicked
    
    public void cargarUsuarios() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblUsuarios.getModel();
        modeloTabla.setRowCount(0);
        
        daoUsuarios usuarioDatos = new daoUsuarios();
        List<Usuario> lstUsuarios = usuarioDatos.listarUsuarios();
        String datos[] = new String[5];
        
        if(rolPasajero){
            for (int i=0;i<lstUsuarios.size();i++) {
                if(lstUsuarios.get(i).getNumeroDocumento().equals(lblNroDoc.getText())) {
                    datos[0] = lstUsuarios.get(i).getNombre();
                    datos[1] = lstUsuarios.get(i).getApellidoPat() + " " + lstUsuarios.get(i).getApellidoMat();            
                    datos[2] = lstUsuarios.get(i).getNumeroDocumento();
                    datos[3] = lstUsuarios.get(i).getUsuario();
                    datos[4] = lstUsuarios.get(i).getRol();
                    modeloTabla.addRow(datos);
                }
            }
            panelRestaurar.setVisible(false);
        } else {
            for (int i=0;i<lstUsuarios.size();i++) {
                datos[0] = lstUsuarios.get(i).getNombre();
                datos[1] = lstUsuarios.get(i).getApellidoPat() + " " + lstUsuarios.get(i).getApellidoMat();            
                datos[2] = lstUsuarios.get(i).getNumeroDocumento();
                datos[3] = lstUsuarios.get(i).getUsuario();
                datos[4] = lstUsuarios.get(i).getRol();
                modeloTabla.addRow(datos);
            }
            panelActualizar.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActualzarPass;
    private javax.swing.JLabel btnRestaurarPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelActualizar;
    private javax.swing.JPanel panelRestaurar;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
