/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utp.edu.pe.app.tarjeta;

import java.awt.BorderLayout;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import utp.edu.pe.dao.daoCarnes;
import static utp.edu.pe.app.frmPrincipal.content;
import utp.edu.pe.dao.daoTarjetas;
import utp.edu.pe.entity.Tarjeta;
import javax.swing.JOptionPane;

/**
 *
 * @author Jerry Aguilar - U21229611
 */
public class crearTarjeta extends javax.swing.JPanel {

    /**
     * Creates new form crearTarjeta
     */    
    public crearTarjeta() {        
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMontoPasaje = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));
        setPreferredSize(new java.awt.Dimension(770, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Crear Tarjeta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 758, 10));

        jLabel2.setText("SERVICIO:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 95, -1, -1));
        add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 117, 680, 40));

        jLabel4.setText("MONTO PASAJE:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        add(txtMontoPasaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 680, 40));

        jLabel9.setText("DESCRIPCION :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 687, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utp/edu/pe/resources/salvar.png"))); // NOI18N
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        crearTarjeta();
        limpiarCajas();
        
        mainTarjeta mainTarjeta = new mainTarjeta();
        mainTarjeta.setSize(770, 700);
        mainTarjeta.setLocation(0,0);
        
        content.removeAll();
        content.add(mainTarjeta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnGuardarMouseClicked
    
    private void crearTarjeta() {        
        Tarjeta objTarjeta = new Tarjeta();
        daoTarjetas tarjetaDatos = new daoTarjetas();
        String msjRespuesta;
        
        objTarjeta.setServicio(txtServicio.getText());
        objTarjeta.setMontoPasaje(Float.valueOf(txtMontoPasaje.getText()));
        objTarjeta.setDescripcion(txtDescripcion.getText());
        
        
        msjRespuesta = tarjetaDatos.crearTarjeta(objTarjeta);
        JOptionPane.showMessageDialog(this, msjRespuesta);
    }
    
    public void generarCarne() {
        daoCarnes carneDatos = new daoCarnes();        
        int nroCarne = carneDatos.generarCarne();
        String nroCarneFormat = String.format("%0" + 15 + "d", nroCarne);
        
        txtServicio.setText(nroCarneFormat);
    }
    
    private void limpiarCajas() {
        JTextField caja;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)this.getComponent(i);
                caja.setText(null);
            }
        }
        
        JComboBox combo;
        for(int i = 0; i < this.getComponentCount(); i++) {
            if(this.getComponent(i).getClass().getName().equals("javax.swing.JComboBox")) {
                combo = (JComboBox)this.getComponent(i);
                combo.setSelectedIndex(0);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMontoPasaje;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
